delete from AULA_UTENTE
delete from INSTALACAO_AULA
delete from INSTALACAO_MODALIDADE
delete from INSCRICAO
delete from UTENTE
delete from AULA
delete from MODALIDADE
delete from INSTALACAO
INSERT INTO UTENTE (NUMUTENTE, NOME, NIF) VALUES ('1', 'Ulisses', '223842389')
INSERT INTO UTENTE (NUMUTENTE, NOME, NIF) VALUES ('2', 'David', '256039682')
INSERT INTO UTENTE (NUMUTENTE, NOME, NIF) VALUES ('3', 'Teresa', '269901841')
INSERT INTO UTENTE (NUMUTENTE, NOME, NIF) VALUES ('4', 'Querubim', '197672337')
INSERT INTO UTENTE (NUMUTENTE, NOME, NIF) VALUES ('5', 'Cicero', '221057552')
INSERT INTO MODALIDADE (NOME, DURACAOMIN, PRECO) VALUES ('Pilates', Time('00:50'), 7)
INSERT INTO MODALIDADE (NOME, DURACAOMIN, PRECO) VALUES ('STEP', Time('00:45'), 10)
INSERT INTO MODALIDADE (NOME, DURACAOMIN, PRECO) VALUES ('GAP', Time('00:50'), 10)
INSERT INTO MODALIDADE (NOME, DURACAOMIN, PRECO) VALUES ('Indoor Cycling', Time('00:55'), 10)
INSERT INTO MODALIDADE (NOME, DURACAOMIN, PRECO) VALUES ('Hidroginastica', Time('00:45'), 15)
INSERT INTO INSTALACAO (NOME, CAPACIDADE) VALUES ('Estudio 1', 20)
INSERT INTO INSTALACAO (NOME, CAPACIDADE) VALUES ('Estudio 2', 15)
INSERT INTO INSTALACAO (NOME, CAPACIDADE) VALUES ('Biclas', 10)
INSERT INTO INSTALACAO (NOME, CAPACIDADE) VALUES ('Piscina 25', 20)
INSERT INTO INSTALACAO_MODALIDADE (Instalacao_NOME, modPermitidas_NOME) VALUES ('Estudio 1', 'Pilates')
INSERT INTO INSTALACAO_MODALIDADE (Instalacao_NOME, modPermitidas_NOME) VALUES ('Estudio 1', 'STEP')
INSERT INTO INSTALACAO_MODALIDADE (Instalacao_NOME, modPermitidas_NOME) VALUES ('Estudio 1', 'GAP')
INSERT INTO INSTALACAO_MODALIDADE (Instalacao_NOME, modPermitidas_NOME) VALUES ('Estudio 2', 'Pilates')
INSERT INTO INSTALACAO_MODALIDADE (Instalacao_NOME, modPermitidas_NOME) VALUES ('Biclas', 'Indoor Cycling')
INSERT INTO INSTALACAO_MODALIDADE (Instalacao_NOME, modPermitidas_NOME) VALUES ('Piscina 25', 'Hidroginastica')
